### ISSUE TITLE
Proposal: support setting the step label dynamically

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#10]
Currently, step labels are set on script load when we evaluate the script. We use the label from the first argument to the step() function.

It would be useful to be able to change this at runtime, in order to indicate what happened in the report.

#### `this.label = "foo"`

This would work by introducing a local scope to steps (currently null) during runtime. The local scope would expose one writeable property: `label`, which ordinarily resolves to the name of the step.

After the step runs, the value of label is written to a property called label on the `Step` object and used in reporting.

#### Interpolation

This method would work by interpolating strings in the step title using test data properties.

```
type Row = {itemName: string}

step("Item: {itemName}", (browser, row:Row))
```

Limitation here is that you could only do it using test data, and not any string computed within the step. This is largely ideological, how much do we want to allow customers to do that?

#### Rework the VM

Last approach would mean redesigning the VM so that we can eval steps at runtime. There are obvious reasons this isn't ideal.

**Comment by mkj28** [comment]
I think this may be useful for doing loops on steps? For example I want to log in once and then repeat certain operation n times - but each of them should be treated by reports as individual operation/step.

**Comment by ivanvanderbyl** [comment]
@mkj28 I'm curious how you would keep the UI in correct state? We have a proposal to add a 'before' action which can simplify things like login, but it's worth nothing that the login session will be reset after each loop, so this is basically the same as making the first step the login step.
