### ISSUE TITLE
Cannot initialize project: Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by dorrogeray** [flood-io/element#103]
**Describe the bug**
I am unable to initialize the project:
![image](https://user-images.githubusercontent.com/4999006/74091305-4e840680-4ab6-11ea-97a7-f773e727114c.png)

**To Reproduce**
1. `yarn global add @flood/element-cli@beta`          (using beta because of https://github.com/flood-io/element/issues/90)
2. `element init ./tests`

**Expected behavior**
Project initializes without error.

**Desktop:**
 - OS: Ubuntu 18.04
 - Node.js version: 12.13
 - Version 1.0.10-beta.45

**Additional info**

I believe this happens because of this line: https://github.com/flood-io/element/commit/3324a350ae01fb6f7732893d5af4992af96135ff#diff-279de4e110beb60b09dcafc85ee9ec3bR5

This causes index.js not to be generated, and this then causes the error: `Please verify that the package.json has a valid "main" entry`

**Comment by ivanvanderbyl** [comment]
I've fixed this in the latest beta.

**Comment by ivanvanderbyl** [comment]
Resolved in beta-52.
