### ISSUE TITLE
sendKeys Key combinations (incl cross-platform)

### ISSUE THREAD

**Issue by lachie** [flood-io/element#13]
I'd like to be able to do key combos using `browser.sendKeys()` and the `Key` enum to simulate typing on a keyboard.
Additionally I need to send different key combinations depending on the platform the test script will run on.

Command-Key combos might not be possible on mac, but there are still plenty of web-apps which handle keyboard input directly for key combos.
https://github.com/GoogleChrome/puppeteer/issues/1313

When developing the test script using Element on my Mac I'd copy something with CMD-C, but when the script runs on flood.io it'll be running under linux, where the equivalent combo is CTRL-C. This point may be moot depending on puppeteer#1313

A simple API would be to allow grouping `sendKeys` inputs into arrays: `browser.sendKeys( [Key.CONTROL, "A"] )` would press CTRL-A

Not all keys [listed](https://github.com/GoogleChrome/puppeteer/blob/v1.8.0/lib/USKeyboardLayout.js) are included in the Key enum

**Comment by jrizio** [comment]
A customer has requested for this very same functionality. Puppeteer has an interesting approach as follows:

`page.keyboard.down('Shift', {delay: 250});
  page.press('ArrowLeft', {delay: 250});
  page.keyboard.up('Shift', {delay: 250});`

It also appears that the above keyboard functionality is the preferred method in Puppeteer for doing key combinations with the added accuracy of using delay times too (if needed).

**Comment by ivanvanderbyl** [comment]
I think we can adopt something similar to this, just like we did with the `browser.mouse` PR.

**Comment by jrizio** [comment]
We have access to the `page` object as of 1.0.5 so we'll be able to use this functionality based on Lachie's improvements.

**Comment by ivanvanderbyl** [comment]
```
browser.keyboard.pressCombination("CTRL+A")
```
