### ISSUE TITLE
setting's properties is not apply to chromium - macOS

### ISSUE THREAD

**Issue by linklink36** [flood-io/element#130]
**Describe the bug**
Look like setting's properties is not apply to chromium

**To Reproduce**
1.Setting script:
`export const settings: TestSettings = {
  device: Device.iPadLandscape,
  // ingress requires proper user agent
  userAgent:
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36',
  clearCache: true,
  disableCache: true,
  clearCookies:true,
  screenshotOnFailure: true,
};`
2. Check value of setting before navigate to page:
`step('Agent: Navigate to Home Page', async browser => {
    console.log("cacheDisable: "+await browser.settings.disableCache);
    console.log("clearCache: "+await browser.settings.clearCache);
    console.log("clearCookie: "+await browser.settings.clearCookies);
    await browser.visit('https://page_url', {
      waitUntil: 'load',
      timeout: 60000,
    });
  });`
==> all return true
Actual result: From 2nd iteration, when navigate to page, it's already logged in to the page instead of showing login screen as 1st iteration.
**Expected behavior**
Cache and cookie should be clear if with provided setting. 

**Screenshots**
NA

**Desktop :**
 - OS: macOS
 - Node.js version: 12.16.1
 - Version 1.0.10

**Additional context**

**Comment by huyennbl** [comment]
Hi @linklink36, 
First of all, depends on which pkg manager you're using, please try upgrade to element-cli 1.2.3 via 
```
npm install -g element-cli@1.2.3
```
or
```
yarn add global element-cli@1.2.3
```
Then retry your script. I currently using this version and it looks like this problem got fixed. I tested with my script, login to amazon.com with 3 loops, and it works well.

If the problem still persists in element-cli version 1.2.3, please provide the service url that you're trying to login to, I'll have a look at them.
