### ISSUE TITLE
Support a configuration file for reusing a config across tests within a project/repo

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#133]
Similar to how jest does it. See https://github.com/flood-io/element/projects/1#card-31266795

Features:

- Support configuring element from a file e.g. `element.config.js`
- Ability to specify all standard CLI flags and options
- Ability to specify a path to element tests e.g. `testPathMatch: "tests/performance/*.perf..ts"`

```
element run
```

Load the config, and run all tests.

**Comment by phileba** [comment]
I think we should allow the user to decide to load a config file as a CLI flag like:
`element run --config-file='./element.config.js'`
How do you think @ivanvanderbyl?

**Comment by ivanvanderbyl** [comment]
Prior art: https://github.com/facebook/jest/tree/master/packages/jest-config

I'm thinking something along the lines of `element-config`..

**Comment by ivanvanderbyl** [comment]
Initialize new config:

```
element --init // generates config file
```
