### ISSUE TITLE
Getting Error "responded with status code 401. Element expected a response code 200-299 or 300-399"

### ISSUE THREAD

**Issue by vddhaya** [flood-io/element#146]
I am facing an issues in launching the application.

Browser.visit(www.myurl.com) 

My URL is having internal redirection (HTTP: 401 is expected response code during launch)

My typescript is throwing an "Element tried to visit the URL www.myurl.com responded with status code 401."

**Comment by ivanvanderbyl** [comment]
Hi @vddhaya — this is something we're trying to fix in a coming release, but for now the easiest workaround is this:

```ts
try {
await browser.visit("site.com")
catch {}
```

**Comment by HieuLeKMS** [comment]
I've fixed this in the latest beta
