### ISSUE TITLE
Unknown net error occurred: no response

### ISSUE THREAD

**Issue by allefoli** [flood-io/element#147]
I've got a test script that hit this error every time if launched on flood and randomly but rarely on local environment:
`in call browser.visit():
Error: An unknown net error occurred: no response (kind: http / subKind: no-response)

Detail:
Documentation needed! Please report this at https://github.com/flood-io/element/issues so that we can improve Element!`

or in Flood

`[01] error: =!=> Failure in Start: Error: An unknown net error occurred: no response (kind: http / subKind: no-response).`

Strangely the screenshot taken on error show the page correctly loaeded, and also in the exported network trace there is nothing strange.

`{
"op": "network",
"label": "Start",
"sampleCount": 1,
"errorCount": 0,
"startTime": 1588490571325.978,
"endTime": 1588490571792.04,
"url": "https://XXXXXXXXXXX/Account/Login",
"requestHeaders": "Host: XXXXXXXXXXXX\nConnection: keep-alive\nUpgrade-Insecure-Requests: 1\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36\nSec-Fetch-Dest: document\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9\nSec-Fetch-Site: none\nSec-Fetch-Mode: navigate\nSec-Fetch-User: ?1\nAccept-Encoding: gzip, deflate, br\nAccept-Language: en-US",
"responseHeaders": "http/1.1 OK\nCache-Control: no-cache, no-store, must-revalidate\nPragma: no-cache\nContent-Length: 30315\nContent-Type: text/html; charset=utf-8\nContent-Encoding: gzip\nExpires: -1\nVary: Accept-Encoding\nServer: Microsoft-IIS/10.0\nSet-Cookie: ASP.NET_SessionId=XXXXXX; path=/; HttpOnly; SameSite=Lax\nASP.NET_SessionId=XXXXXX; path=/; HttpOnly; SameSite=Lax\n__RequestVerificationToken=XXXXXXX; path=/; HttpOnly\nX-AspNetMvc-Version: 5.2\nX-Frame-Options: SAMEORIGIN\nSAMEORIGIN\nX-AspNet-Version: 4.0.30319\nX-Powered-By: ASP.NET\nDate: Sun, 03 May 2020 07:22:51 GMT",
"responseData": "",
"sourceHost": "XX.XX.XX.XX"
}`

On local environment is not reproducible, as i said it appears randomly. What i see with no-headless is that on browser.visit the page is loaded twice, the error hits on second load.

**Comment by allefoli** [comment]
This is the catched error from Flood
`2020/05/04 11:19:53
StructuredError
2020/05/04 11:19:53
at Browser.<anonymous> (/app/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:27:23)
2020/05/04 11:19:53
at Generator.next (<anonymous>)
2020/05/04 11:19:53
at /app/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:8:71
2020/05/04 11:19:53
at new Promise (<anonymous>)
2020/05/04 11:19:53
at __awaiter (/app/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:4:12)
2020/05/04 11:19:53
at Browser.descriptor.value (/app/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:23:20)
2020/05/04 11:19:53
at Object.base.apply (/app/node_modules/vm2/lib/contextify.js:519:32)
2020/05/04 11:19:53
at /data/flood/files/load-test.perf.ts:131:27
2020/05/04 11:19:53
at /data/flood/files/load-test.perf.ts:109:71 {
2020/05/04 11:19:53
_structured: 'yes',
2020/05/04 11:19:53
wrappedUnstructured: false,
2020/05/04 11:19:53
source: 'browser',
2020/05/04 11:19:53
data: {
2020/05/04 11:19:53
url: 'https://xxxxxxxx/Account/Login',
2020/05/04 11:19:53
_kind: 'net',
2020/05/04 11:19:53
kind: 'http',
2020/05/04 11:19:53
subKind: 'no-response'
2020/05/04 11:19:53
2020/05/04 11:19:53
originalError: undefined,
2020/05/04 11:19:53
callContext: 'browser.visit'`

**Comment by phileba** [comment]
@allefoli can you send us your script then we can reproduce?

**Comment by phileba** [comment]
I've created another ticket https://github.com/flood-io/element/issues/203 for this issue.
