### ISSUE TITLE
Unable to use await browser.sendKeys(Key.ENTER); in script

### ISSUE THREAD

**Issue by duongnapham** [flood-io/element#152]
**Describe the bug**
Unable to press enter with code: await browser.sendKeys(Key.ENTER);
 
**To Reproduce**
In my test script, I have defined configuration as below:

> export const settings: TestSettings = {
	screenshotOnFailure: true,
	disableCache: true,
	clearCache: true,
	clearCookies: true,
	actionDelay: 15,
	stepDelay: 15,
	waitTimeout: 120,
	waitUntil: 'visible',
}

One of my step, I have defined code as below:

> await browser.click(searchButton);
    await browser.type(searchTextbox, searchKeyword);
    await browser.sendKeys(Key.ENTER);
    await browser.wait(Until.elementIsVisible(searchResults));
    await browser.takeScreenshot();

When running it, it have seen that the cursor has been clicked and typed correctly search text and no search result displays.

**Expected behavior**
Search result in UI should be displayed after pressing Enter keyboard.

**Desktop (please complete the following information):**
 - OS: [10.14.6]
 - Node.js version: [10.16.3]

**Comment by huyennbl** [comment]
`sendKey()` has its own `waitUntil` so there's maybe conflict between `sendKey()` and TestSettings' `waitUntil: 'visible'`
Please try again without `waitUntil: 'visible'` in TestSettings and it should work
