### ISSUE TITLE
"browser" is not available in v1.2.3 if you don't have a previous version installed

### ISSUE THREAD

**Issue by georjino** [flood-io/element#169]
When you install v1.2.3 (fresh install) without having a previous version on your machine, "browser" will not be downloaded, therefore you cannot run any script.

**Comment by phileba** [comment]
hi @georjino, it seems an issue of puppeteer, detail https://github.com/puppeteer/puppeteer/issues/2173, so you can try this one:
```
sudo npm install --unsafe-perm -g @flood/element-cli
```
