### ISSUE TITLE
Enhance unit of waitTimeout from ms to second makes it more consistently in TestCase settings.

### ISSUE THREAD

**Issue by duongnapham** [flood-io/element#183]
**Flood element define the unit of waitTimeout in TestCase setting is milliseconds while other properties are second. .**
Please enhance it as second to make it more consistently other properties

**Comment by ai-flood** [comment]
Integrating with https://www.npmjs.com/package/ms, should we change the current WaitTimeout type from a number to a string or both them? @phileba @sonnguyenmau

**Comment by phileba** [comment]
> Integrating with https://www.npmjs.com/package/ms, should we change the current WaitTimeout type from a number to a string or both them? @phileba @sonnguyenmau

I think we should change those types to String, the value should be `'10s'` or `'2m'` or `'100'`. Supporting both types is not a good way to enhancement later I think. How do you think @ivanvanderbyl ?
