### ISSUE TITLE
Error: net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by enriquecss** [flood-io/element#194]
**Describe the bug**
If there are any network issues or timeout execution breaks abrupted

Error: net::ERR_TIMED_OUT at https://mysite.com

**To Reproduce**
1. Go to 'element run mytesyscript'
2. After a timeout on Chromium browser
3. See Error: net::ERR_TIMED_OUT at https://mysite.com

**Expected behavior**
It should be a specific error about timeout

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Node.js version: v14.0.0

**Additional context**

**Comment by phileba** [comment]
@enriquecss can you send me your sample script or name of the action that makes this error occurs

**Comment by enriquecss** [comment]
Sure, I'm using the following instruction to navigate 

	step('Step 4 Do some actions', async browser => {
		await browser.page.goto('https://mango-staging.impira.com/o/UAT-TS/mango/sheets/3e76cd9af256d747')
		await browser.focus(By.css(".Header-createNew .SVGInline"))
		await browser.click(By.css(".Header-createNew .SVGInline"))
	})

**Comment by phileba** [comment]
> Sure, I'm using the following instruction to navigate
> 
> ```
> step('Step 4 Do some actions', async browser => {
> 	await browser.page.goto('https://mango-staging.impira.com/o/UAT-TS/mango/sheets/3e76cd9af256d747')
> 	await browser.focus(By.css(".Header-createNew .SVGInline"))
> 	await browser.click(By.css(".Header-createNew .SVGInline"))
> })
> ```

you should use `await browser.visit('https://mango-staging.impira.com/o/UAT-TS/mango/sheets/3e76cd9af256d747')`
then you will see an error likes:
```
incall browser.visit():
Error: Navigation timeout of 30000 ms exceeded
```

**Comment by enriquecss** [comment]
That's correct, seeing the error Navigation timeout, is there any way to navigate to another webpage as puppeteer does?

Thanks

**Comment by b-remo** [comment]
@enriquecss any luck with the above scenario? I've been stuck with the same issue.

**Comment by phileba** [comment]
@b-remo you can try this one:
step('Step 4 Do some actions', async browser => {
	await browser.visit(url, { waitUntil: 'load' })
})

**Comment by b-remo** [comment]
thank you @phileba this works

**Comment by enriquecss** [comment]
I'm wondering if there is any way to change the timeout of 30000

Thanks

**Comment by phileba** [comment]
@enriquecss you can change the `waitTimeout` in the TestSetting, detail https://element.flood.io/docs/guides/test-settings#waittimeout.
e.g:
```ts
export const settings: TestSettings = {
	waitTimeout: 20000,
}
```
