### ISSUE TITLE
element generate on CLI not creating test file

### ISSUE THREAD

**Issue by carltondickson** [flood-io/element#197]
**Describe the bug**
Running `element generate test-file` doesn't create a test file

**To Reproduce**

1. `element init ./element-project`
2. Accept all defaults
3. `cd element-project`
4. `element generate SomeTest.ts`

I get null as the output and no test file

`$ element generate SomeTest.ts
Using local version of Element
null
`

**Expected behavior**
I expected a test file to have been created

**Screenshots**

**Desktop (please complete the following information):**
- OS: macOS
- Node.js version: v12.18.0
- NPM version: 6.14.5
- Element version: 1.2.3

**Additional context**
I did upgrade npm just before running through the tutorial

**Comment by phileba** [comment]
Hi @carltondickson, it seems like a bug so we will fix it in the next release.

**Comment by phileba** [comment]
Fixed on https://github.com/flood-io/element/pull/166
