### ISSUE TITLE
While running flood element scripts , Error :  Checking for Updates failed

### ISSUE THREAD

**Issue by mailboxskumar** [flood-io/element#200]
Unable to check element version and execute element scripts due to update check failed error

**To Reproduce**
1. Open node js command prompt
2. Type element --version command
3. See update failed check error

**Expected behavior**
element version should display and scripts should execute by default

**Screenshots**
attached herewith

**Desktop (please complete the following information):**

 - OS: Windows10
 - Node.js version: v12.16.1
 - Version: element version : 1.2.3

[flood-element-error](https://user-images.githubusercontent.com/32169662/86147817-78969d80-bb17-11ea-9818-c7d7e492b899.png)

**Comment by phileba** [comment]
fixed on latest version
