### ISSUE TITLE
Error: net::ERR_CONNECTION_RESET at

### ISSUE THREAD

**Issue by rajasekaranmanoharan2** [flood-io/element#205]
Shows Error: net::ERR_CONNECTION_RESET at for a specific URL site. When check in --no -headless mode, shows the 'connection is not secure in this site'. Manually it works correctly

import { step, TestSettings, Until, By, Device } from '@flood/element'
import * as assert from 'assert'

export const settings: TestSettings = {

//loopCount: -1,
screenshotOnFailure: true,
clearCache: true,
disableCache: true,
ignoreHTTPSErrors: false,
actionDelay: 8,
stepDelay: 10,
   }
   
   /**
 * Its52dotcom
 * @version 1.0
 */
 export default () => {
	step('Test: Launch URL', async browser => {
		// visit instructs the browser to launch, open a page, and navigate to https://www.its52.com/
		await browser.visit('https://its52.com/')
		let pageTextVerify = By.visibleText("Idaratut Ta'reef al Shakhsi")
	await browser.wait(Until.elementIsVisible(pageTextVerify))	
	//await browser.takeScreenshot()
	})
	
	step('Test: Login page', async browser => {
		
	await browser.type(By.id("txtUserName"), "30322032")
	await browser.type(By.id("txtPassword"), "y1261")
	const loginButton = await browser.findElement(By.id("btnLogin"))
	await  loginButton.click()
	await browser.wait(Until.elementIsVisible(By.id("drop1")))
	//await browser.takeScreenshot()
		})
		
	step('Test: Home page', async browser => {
		
	const MyDetailButton = await browser.findElement(By.id("drop1"))
	await  MyDetailButton.click()
	const FamilyTreeButton = await browser.findElement(By.xpath("//*[@id='menu1']/li[3]/a"))
	await  FamilyTreeButton.click()
	await browser.wait(Until.elementIsVisible(By.xpath("//*[@id='BoxStart1_divHeading']/div[1]")))
	//await browser.takeScreenshot()
		})
		
	
 }

**Comment by phileba** [comment]
hi @rajasekaranmanoharan2, I've tried the navigation script and it works fine. What version of the element are you using?
