### ISSUE TITLE
Increase timeout

### ISSUE THREAD

**Issue by ahmadSaeedGoda** [flood-io/element#223]
+1s info: ===> Step 'Start'
step error -> failed
+31s error: 

in call browser.visit():
Error: Navigation timeout of 30000 ms exceeded

Detail:
Documentation needed! Please report this at https://github.com/flood-io/element/issues so that we can improve Element!

+31s error: xxxx Step 'Start' failed
+31s info: ---> Step 'Start' finished
failed, bailing out of steps
+31s info: Iteration completed in 30559ms (walltime)
+31s info: Test completed after 1 iterations

**Comment by phileba** [comment]
you can increase the timeout in the test settings, details https://element.flood.io/docs/1.0/guides/test-settings#waittimeout
