### ISSUE TITLE
Loading test data overrides previously loaded data

### ISSUE THREAD

**Issue by andybluntish** [flood-io/element#23]
Loading test data assigns to the `testData` property, so subsequent calls to `TestData` methods in a script override preciously loaded data.

For example, given

```
TestData.fromData([ 'foo', 'bar', 'baz' ])
TestData.fromData([ 'red', 'green', 'blue' ])
```

the second call to `fromData` will override the data loaded from the first, and only `red`, `green`, `blue` values will be available in steps. This same behaviour exists for `fromData`, `fromCSV`, `fromJSON`, or a combination of any of them.

Was this an intentional design decision, or is there another API for achieving this? If so, we should document either way. Otherwise, are there downsides to enabling loading data from multiple sources?

**Comment by lachie** [comment]
It's intentional, but interested to hear how it could work otherwise.
You can get an instance of test data and pass through suite.withData, or use the side effected TestData.withX without suite.

**Comment by andybluntish** [comment]
If it's intentional that's fine, I just ran into it when messing around and was surprised—I guess I wanted the second call to append to the data.

I was playing around with Faker and trying to augment CSV data with some random values, so perhaps some enumerable-type methods on TestDataSource could be useful for that (e.g. map, concat).

This might not be a realistic use case though.

(aside: I was having trouble getting a suite setup, which I'll ping you about when you get back)

**Comment by andybluntish** [comment]
Closing as "works as expected".
