### ISSUE TITLE
How to run multiple Element scripts in one Stream? if not, how to merge the two scripts in one file?

### ISSUE THREAD

**Issue by sreenath3736** [flood-io/element#235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sreenath3736** [comment]
As understood, flood does not support running of multiple element scripts in one stream.This will not be going to simulate actual load test scenario that runs with the multiple scenarios with different user load .
Is there any thoughts to bring this feature in Flood like other tools load test scenarios?

**Comment by phileba** [comment]
Hi @sreenath3736, sorry for the late response, actually we don't support running multiple scripts at the same time, but your idea sounds interesting, we will consider it in the next release.
Thanks.
