### ISSUE TITLE
Ensure type definitions are loaded correctly when compiling

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#3]
Currently if you run a script it will complain about not finding the type definitions, even if you declare `@flood/chrome` or `@flood/element`. This is probably an issue with resolving.

```shell
flood-challenge.ts:1:53 - error TS2307: Cannot find module '@flood/chrome'.

1 import { suite, By, Key, Until, TestSettings } from '@flood/chrome'
                                                      ~~~~~~~~~~~~~~~
```

**Comment by lachie** [comment]
I think this is fixed, please reopen if not.
