### ISSUE TITLE
Add browser.url() method

### ISSUE THREAD

**Issue by nhanflood** [flood-io/element#320]
**Is your feature request related to a problem? Please describe.**
Currently, if we want to get the current URL we need to use puppeteer page. Something like `brower.page.url()`

**Describe the solution you'd like**
`browser.url()` will be better, and looks like more Element way.

**Describe alternatives you've considered**

**Additional context**

**Comment by honglax** [comment]
Hi @nhanflood, we are going to release this API with Element version 1.4. Thank you for your suggestion.
