### ISSUE TITLE
element init command does not create a valid test file in 2.0.0-beta.24

### ISSUE THREAD

**Issue by FilipB** [flood-io/element#334]
**Describe the bug**
`element init` command does not create a valid test file in 2.0.0-beta.24

**To Reproduce**
1. run `element init test` with default values
2. `cd test`
3. `element run test.perf.ts`

**Expected behavior**
Scenario should be successful.

**Actual behavior**
Step 2 fails with:
 ✘ Step 'Step 2 find first heading' failed (147ms)
      cdpSession.send: Protocol error (Overlay.highlightNode): Either nodeId, backendNodeId or objectId must be specified
  Cannot read property 'options' of undefined

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Node.js version: v12.18.2
 - Version 2.0.0-beta.24

**Comment by phileba** [comment]
the element 2.0.0-beta is no longer exists, you can try again with the element 1.4.0-beta.6 or element 2.0.0-canary.13, sorry for this inconvenient.

**Comment by FilipB** [comment]
Still the same issue with 2.0.0-canary.14

**Comment by honglax** [comment]
We're going to take a look at this and release the fix asap. Thanks for your report.

**Comment by honglax** [comment]
Hi @FilipB, this issue is fixed on `Element 2.0.0-canary.19`. Feel free to check it out. Thank you.
