### ISSUE TITLE
Run multiple instances of element script locally

### ISSUE THREAD

**Issue by craigsmitham** [flood-io/element#38]
It would be great to run small-scale load tests locally using element scripts. We've also considered just writing vanilla pupetter scripts and using something like https://www.npmjs.com/package/puppeteer-loadtest.

Does the element CLI support running multiple instances of a script locally in parallel?

**Comment by phileba** [comment]
fixed on the latest beta version

**Comment by phuthanhta** [comment]
Hi there, is there any sample that I can follow to do this?
