### ISSUE TITLE
Support the getCookie() API

### ISSUE THREAD

**Issue by tranphieu97** [flood-io/element#380]
**Is your feature request related to a problem? Please describe.**
When I working with the cookie in my Element project, I have to use the` evaluate()` function and the JS code to get the cookie string and some steps to the get the whole information of my cookie. 

**Describe the solution you'd like**
So, the idea is supporting an API for get the cookie properties by its name like 
`const myCookie = getCookie('cookieName')`

**Describe alternatives you've considered**

**Additional context**

**Comment by honglax** [comment]
Hi @tranphieu97, new API `browser.getCookies()` has been released in Element@canary-17. Here is the documentation of this.
```
browser.getCookies(filterBy?: {urls?: string | string[], names?: string | string[]}): Promise<Cookie[]>

// Returned type
[
  {
      name: string,
      value: string,
      domain: string,
      path: string,
      expires: number, **Unix time in seconds**
      httpOnly: boolean,
      secure: boolean,
      sameSite: "Strict"|"Lax"|"None"
  }
]
```

Thank you for your suggestion.
