### ISSUE TITLE
Response Time in app.flood is empty when setting responseTimeMeasurement to 'page' or 'network'

### ISSUE THREAD

**Issue by FilepCsaba** [flood-io/element#42]
When trying to test my Element scripts in flood, if i set the responseTimeMeasurement to 'page' or 'network', as per the documentation, i get no response time, only Transaction Rate and Current Users.

**To Reproduce**
1. Set responseTimeMeasurement to 'page' in your element script
[Documentation](https://element.flood.io/docs/1.0/api/Settings)
2. Upload the script to a Stream
3. Run a Flood

**Expected behavior**
I expect to see full page load times as mentioned in the documentation:
* STEP: Record the document loading response time. This is usually what you consider response time on paged web apps.

**Screenshots**
<img width="1267" alt="Screenshot 2019-05-22 at 09 59 36" src="https://user-images.githubusercontent.com/50576803/58159155-37795c00-7c7c-11e9-8064-f4c3ffcc834d.png">

Code Sample:
* Test Settings:
`export const settings: TestSettings = {
	clearCache: true,
	disableCache: true,
	screenshotOnFailure: true,
	clearCookies: true,
	actionDelay: 0,
	stepDelay: 0,
	DOMSnapshotOnFailure: true,
	responseTimeMeasurement: 'page',
	waitTimeout: 180,
}`

* The Step:
`step('Test: Reach the main page', async browser => {
	await browser.visit(<URL>)
	await browser.wait(Until.elementIsVisible(Header_Icon))
	await browser.wait(Until.elementIsVisible(Shop_Button))
	await browser.wait(Until.elementIsEnabled(Search_Field))
	await browser.wait(Until.elementIsVisible(Cart_Icon))
	await browser.wait(Until.elementIsVisible(Footer_Icon))
	await browser.wait(Until.elementLocated(Product_List))
})`

**Comment by ivanvanderbyl** [comment]
@FilepCsaba thanks for reporting. I'll investigate this and try to get it fixed in the next release.

**Comment by phileba** [comment]
@FilepCsaba does it occur on el element@1.2.3?
