### ISSUE TITLE
Handle multiple Tabs/Windows

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#47]
Add support for switching tabs or windows in much the same way we do with Frames, using the `TargetLocator`.

**Comment by ivanvanderbyl** [comment]
I've made some progress on this, but I realised the APIs needed to change a bit internally to target the newly opened window. This requires changing `browser.wait` to return the Window handle, instead of a boolean. Which shouldn't really break anything.

**Comment by HHecthor** [comment]
IS there any update on this? Thanks in advance

**Comment by aHectorMa** [comment]
Any updates on this? Thanks

**Comment by ivanvanderbyl** [comment]
@aHectorMa we're still working on it. The plan is to release the current `beta` as `stable` before adding more features, as there's a lot of internal changes which we should release first.
