### ISSUE TITLE
Separate grid & dev runners

### ISSUE THREAD

**Issue by lachie** [flood-io/element#5]
"Grid mode" includes `Influx` reporter & flood env var configuration/metric identifier
"Dev mode" includes `Console` reporter & command line configuration

e.g. env vars handled in the VM, extract to grid runner a la `tosca-flood` `Grid/Environment.ts`
https://github.com/flood-io/element/blob/feature/open-source-everything/packages/element/src/runtime/VM.ts#L188-L208

**Comment by lachie** [comment]
Implemented!

**Comment by ivanvanderbyl** [comment]
I owe you many 🍻!
