### ISSUE TITLE
Support --watch to rerun a test when the script file changes

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#7]
Maybe use watchman or nodemon under the hood.

**Comment by ivanvanderbyl** [comment]
Closing, I believe this is implemented.

**Comment by ivanvanderbyl** [comment]
Actually, just saw your bug on the checklist. Reopening.

**Comment by lachie** [comment]
I tried it again in VS Code and it worked fine :man_shrugging:
