### ISSUE TITLE
Ability to mark a step as a recovery step

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#70]
The idea behind this would be to declare a step which runs when any step fails, as a sort of catch-all. This could be used when the state of a page is not as expected, or authentication fails requiring starting at step 1 again.

```ts
step.recovery(async browser => {
  ...
})

// or with info

type RecoveryInfo = {
  failedStep: string
  reason: FailureReason
}

enum FailureReason {
  Timeout
  ElementNotFound
  PageCrashed
  // etc
}

step.recovery(info: RecoveryInfo, async browser => {
  ...
})
```

**Unknowns:**

- Need to think about how to redirect to the correct step afterward
- Should recovery be associated with a single step?

**Comment by ivanvanderbyl** [comment]
Related to #150

**Comment by phileba** [comment]
@ivanvanderbyl  I think we can support this as the following:
```
step.recovery(async (browser, step) => {
  //do something to recover the step fails
  return true | false // may return data to handle sth.
})
```
the workflow I think is on the running loop of `steps`, if some `step` has failed, we can call the predicate recovery => when finished if success, continues the loop to the next step => resolve your first question, if it's still failed, throw errors.
I think we should associate the recovery to a single step, depends on the inputted step so we can define what the behavior of the recovery step should do.

**Comment by ivanvanderbyl** [comment]
Interesting ideas. So the use cases I have in mind are:

- Handling an unexpected state change in the UI, such as a popup
- Handling testing a ticket sale pipeline where the event sells out, and instead of completing the sales process we just want to show the sold out screen. The use could be redirected here from any step within the pipeline.
- An error page appeared that prevented the step from completing

In the recovery step, we'd probably want to redirect, or click something, or reload. Then either retry the previous step, or move to another step. To do this, I figure we have a few options:

1. Return `true` to retry
2. Return `false` to go to the first step
3. Throw an error/assertion failure to fail the current user

We could take this further and do something like this:

```ts
// global recovery
step.recovery(async browser => {})

// Step 1 recovery
step.recovery("Step 1", async browser => {
  ... do stuff

  // goto(...) is a helper to instruct what to do
  return goto("Step 5")
})
```

**Comment by phileba** [comment]
> Interesting ideas. So the use cases I have in mind are:
> 
> * Handling an unexpected state change in the UI, such as a popup
> * Handling testing a ticket sale pipeline where the event sells out, and instead of completing the sales process we just want to show the sold out screen. The use could be redirected here from any step within the pipeline.
> * An error page appeared that prevented the step from completing
> 
> In the recovery step, we'd probably want to redirect, or click something, or reload. Then either retry the previous step, or move to another step. To do this, I figure we have a few options:
> 
> 1. Return `true` to retry
> 2. Return `false` to go to the first step
> 3. Throw an error/assertion failure to fail the current user
> 
> We could take this further and do something like this:
> 
> ```ts
> // global recovery
> step.recovery(async browser => {})
> 
> // Step 1 recovery
> step.recovery("Step 1", async browser => {
>   ... do stuff
> 
>   // goto(...) is a helper to instruct what to do
>   return goto("Step 5")
> })
> ```

cool, I think we try this one

**Comment by ivanvanderbyl** [comment]
Hmm yeah, interesting point, maybe we ignore the `goto` for now until we identify a real need and use case. I think some things will become more clear when we have the recovery handler implemented

**Comment by phileba** [comment]
I think we should go with that thing: after finishing the recovery step, we will decide what is the next step that we should go, e.g: if the user wants to retry `step 3`, they should use `goto('Step 3')` or wants to run the first step, they can write `goto('Step 1')`. if we do not define anything, just keep the default behavior, continues the next step in the loop.
