### ISSUE TITLE
javascript alert window

### ISSUE THREAD

**Issue by antoniojimenez-flood** [flood-io/element#76]
**Is your feature request related to a problem? No, it's a feature request

**Describe the solution you'd like**
Ability to handle Javascript alert windows with Flood Element

**Describe alternatives you've considered**

**Additional context**

**Comment by ivanvanderbyl** [comment]
This is already supported :)

```
step('Handle alert', async browser => {
  let dialog = await browser.wait(Until.alertIsPresent())
  await dialog.accept()
})
```

**Comment by wilsonmar** [comment]
@ivanvanderbyl if this has been created, we should update https://wilsonmar.github.io/flood-the-internet/#challenges-on-the-internet-app, which has a page to test actual events.

**Comment by steveb85** [comment]
Is there a problem with this in 2.0? I can't for the life of me get it to work.
