### ISSUE TITLE
Custom HTTP Headers

### ISSUE THREAD

**Issue by jrizio** [flood-io/element#8]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to add custom HTTP Headers - i.e to be able to follow different client flows for an A/B test as well as setting different Headers for other testing/environment config purposes.

**Describe the solution you'd like**
It would be great to be able to add/set custom HTTP headers globally and/or on a step basis.

Something like .setExtraHTTPHeaders in Puppeteer: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetextrahttpheadersheaders

**Comment by jiffypopjr** [comment]
This is critical for us to use the platform, all our authentication and verification uses http headers.

**Comment by ivanvanderbyl** [comment]
This is now in the latest beta release.
