### ISSUE TITLE
Specifying Chrome version when testing locally

### ISSUE THREAD

**Issue by cpereyra5199** [flood-io/element#84]
I have not been able to find any documentation around specifying the chrome version.  The documentation I found referenced --chrome-version, which I don't see available when running element run help.  I only see --chrome, which specifies which version of chrome to use.  However, I'm not sure what type of input is expected?  Could you please point me in the right direction?

Thanks,

**Comment by ivanvanderbyl** [comment]
We'll update the docs for this, but generally, it needs to point to a Chrome binary, which varies by platform.

Example on macOS:

```
element run --chrome=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
```

On Linux it would be something like:

```
element run --chrome=google-chrome-stable
```
