### ISSUE TITLE
Unable to handle browser dialogs that do not appear in the DOM

### ISSUE THREAD

**Issue by aidylewis** [flood-io/element#85]
**Describe the bug**
Unable to handle browser dialogs that do not appear in the DOM. 
The Flood Element spec file use CSS selectors
https://github.com/flood-io/element/blob/37fc2b4c281b41f6d66edb3fb4235f77b7e3c165/packages/element/src/page/conditions/DialogCondition.spec.ts#L30-L57.

I hang on replace.click() which activates the browser dialog. 
```typescript
    await replace.click()
    await browser.wait(Until.alertIsPresent())
    let dialog: Dialog
    await dialog.accept()
```
This is the example provided in your docs.
```typescript
// https://element.flood.io/docs/1.0/api/Waiters
step('Handle alert', async browser => {
  let dialog = await browser.wait(Until.alertIsPresent())
  await dialog.accept()
})
```

accept does not have a method on a Boolean,

**Comment by ivanvanderbyl** [comment]
This is a typing issue, it'll be fixed in the next stable release. Thanks for reporting.

**Comment by phileba** [comment]
@aidylewis you can try this one:
```
step('Test:Handle Prompt', async browser => {
	try {
		const condition = Until.alertIsPresent()
		await browser.visit('alerts.html')
		browser.click('#prompt', { delay: 200 })
		const alert = await condition.waitForEvent(browser.page)
		await alert.accept('phile')
	} catch (err) {
		console.log(`Error: ${err}`)
	}
})

**Comment by steveb85** [comment]
I'm having a lot of trouble with this, and getting the same "accept does not have a method on a Boolean," as @ghost when I use the current example.

**Comment by vipulsharma144** [comment]
> @aidylewis you can try this one:
> 
> ```
> step('Test:Handle Prompt', async browser => {
> 	try {
> 		const condition = Until.alertIsPresent()
> 		await browser.visit('alerts.html')
> 		browser.click('#prompt', { delay: 100 })
> 		const alert = await condition.waitForEvent(browser.page)
> 		await alert.accept('phile')
> 	} catch (err) {
> 		console.log(`Error: ${err}`)
> 	}
> })
> ```

This works , thanks !!
