### ISSUE TITLE
[DOCS] Incorrect example for By.attr

### ISSUE THREAD

**Issue by ghost** [flood-io/element#86]
**By.attr** takes three formal parameters your documentation example suggests two arguments. 

https://element.flood.io/docs/1.0/api/Locators

```Typescript
By.attr('name', 'frame-name')
```

**Comment by ivanvanderbyl** [comment]
This seems to be a bug, I'll check it out

**Comment by phileba** [comment]
@ivanvanderbyl It seems that a typing problem, document updates and this problem will be fixed
