### ISSUE TITLE
`screenshotOnFailure: true` does not create a screenshotOnFailure

### ISSUE THREAD

**Issue by aidylewis** [flood-io/element#87]
I am running headless and can explicitly take a screenshot
```TypeScript
await browser.takeScreenshot()
````
However, the test setting ```screenshotOnFailure: true```, does not take a screenshot upon failure.

**Comment by ivanvanderbyl** [comment]
I've managed to replicate this locally. I'll dig in to fixing it this week.

**Comment by javaadpatel** [comment]
@ivanvanderbyl  I am quite interested in using the screenshotOnFailure feature, is there any way I can help get the bug fixed?

**Comment by ivanvanderbyl** [comment]
Resolved by #124
