### ISSUE TITLE
loopCount setting not working

### ISSUE THREAD

**Issue by UBIKDIVENTIM** [flood-io/element#91]
**Describe the bug**

The loopCount setting used in TestSettings looks to have no effect on the number of iterations.

If I let it to it's default value (-1), when I run the script, it only executes once.

If I set loopCount: 10, I still get only one iteration.

The only way I can have the script running for 'X'  iterations is by setting it in the command :

element run filename --loop-count=10

**To Reproduce**

1. element generate filename
2. element run filename
2.1. Or, add loopCount: X in TestSettings and then : element run filename

**Expected behavior**

2. The script will run infinitely
2.1. The script will run for X iterations

**Desktop (please complete the following information):**

 - OS: Ubuntu [19.10]
 - Node.js version: [12.13.0]
 - Element: [e.g. 1.0.8-stable.1]

**Comment by ivanvanderbyl** [comment]
@dvmarco thanks for reporting, I'll need to investigate this further
