### ISSUE TITLE
Error! Checking for updates failed

### ISSUE THREAD

**Issue by xmaestro** [flood-io/element#94]
**Describe the bug**
I'm trying to install Element CLI using the instruction in Getting Started guide here: https://element.flood.io/. But, i'm getting the below error after installation through NPM:

> $ element --version
Error! Checking for updates failed
Error: Distribution tag stable is not available
    at getMostRecent (/home/rizwan-hussain/.nvm/versions/node/v13.2.0/lib/node_modules/@flood/element-cli/node_modules/update-check/index.js:140:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/home/rizwan-hussain/.nvm/versions/node/v13.2.0/lib/node_modules/@flood/element-cli/node_modules/update-check/index.js:185:12)
    at async doUpdateCheck (/home/rizwan-hussain/.nvm/versions/node/v13.2.0/lib/node_modules/@flood/element-cli/dist/src/element.js:71:24)
    at async Object.main (/home/rizwan-hussain/.nvm/versions/node/v13.2.0/lib/node_modules/@flood/element-cli/dist/src/element.js:40:5)
element <command> [options]

**To Reproduce**
1. Run npm install -g @flood/element-cli
2. Run element -v

**Expected behavior**
It should display installed version of Element

**Desktop (please complete the following information):**
 - OS: Linux rizwanhussain-ThinkPad-X1-Carbon-3rd 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Node.js v13.2.0
 - NPM Version 6.13.1

**Comment by ivanvanderbyl** [comment]
Hi @xmaestro, can you try installing the latest beta and let me know if it works:

```bash
npm install -g @flood/element-cli@beta
```

**Comment by aviationfan** [comment]
I ran that command to get the latest beta
`npm install -g @flood/element-cli@beta`

Do I need to find a fix for these WARNings?
```
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.       
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
```

Sadly my first test run of the beta failed :-(

```
+0s info: workRootPath: tmp/element-results/2020-01-07T195751.543Z
+0s info: testDataPath: .
+0s debug: Loading test script: .\the-dash.ts
process exited - with error
Error: Error: Unable to compile Element script .\the-dash.ts: C:/Users/jjwel/AppData/Roaming/npm/node_modules/@flood/element-cli/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:167:11
    167 interface IteratorResult<T> { }
                  ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
node_modules/@types/node/index.d.ts:167:11 - error TS2300: Duplicate identifier 'IteratorResult'.

167 interface IteratorResult<T> { }
              ~~~~~~~~~~~~~~

  C:/Users/jjwel/AppData/Roaming/npm/node_modules/@flood/element-cli/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

    at Object.<anonymous> (C:\Users\jjwel\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\@flood\element\dist\src\TestScript.js:134:19)  
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jjwel\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\@flood\element\dist\src\TestScript.js:5:58)
```

**Comment by ivanvanderbyl** [comment]
Hi @aviationfan — We've just completed a major refactor of the compiler on windows, can you please try the latest beta >= `1.0.10-beta.39`

Upgrade with:
```
# yarn
yarn global upgrade @flood/element-cli@beta

# or NPM:
npm -g install @flood/element-cli@beta
```
